#!/usr/bin/env bash
# Displays "To infinity and beyond" with a sleep 2
# and displays "I am invincible" when killed

while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible"' SIGTERM
done
